# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "web-car"
  config.vm.synced_folder "sinc/", "/var/www/html/"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "172.16.0.0", netmask: "255.255.0.0"
  config.vm.network "public_network", ip: "10.99.0.0", netmask: "255.255.0.0"
  config.vm.provider "virtualbox" do |vb|
      vb.name ="Web Server"
      vb.memory = 3072
      vb.cpus= 2
  end
end
