# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/ubuntu-server-2004-lts"
  config.vm.hostname = "server-car"
  config.vm.synced_folder "../PR0101/sincr", "/data"
  config.vm.provider "virtualbox" do |vb|
      vb.name ="Ubuntu Server"
      vb.memory = 2048
      vb.cpus= 2
  end
end
